spring:
  application:
    name: reptilian-video
  datasource:
    url: jdbc:mysql://localhost:3306/reptilian_video?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root


logging:
  config: classpath:logback-spring.xml
  file: ${spring.application.name}
  path: D:\log


